<!-- Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ -->
<script setup>
import { onMounted,ref } from 'vue'; import { api } from '../api/oa'; import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(),dashboard=ref({pendingTasks:0,pendingLeaves:0,notices:0}),notices=ref([])
onMounted(async()=>{[dashboard.value,notices.value]=await Promise.all([api.dashboard(),api.notices()])})
const apps=[['考勤打卡','clock-o','/attendance'],['请假审批','records-o','/leave'],['我的待办','todo-list-o','/tasks'],['企业公告','volume-o','/notices']]
</script>
<template><div class="page safe-top"><section class="hero brand-gradient"><div><div class="hello">你好，{{auth.user?.fullName}}</div><div class="muted-light">{{auth.user?.departmentName}} · {{auth.user?.position}}</div></div><van-icon name="setting-o" size="24"/></section><section class="card stats"><div class="stat-row"><div><div class="stat-value">{{dashboard.pendingTasks}}</div><div class="stat-label">待办事项</div></div><div><div class="stat-value">{{dashboard.pendingLeaves}}</div><div class="stat-label">审批中</div></div><div><div class="stat-value">{{dashboard.notices}}</div><div class="stat-label">企业公告</div></div></div></section><h2 class="section-title">快捷办公</h2><section class="grid"><router-link v-for="app in apps" :key="app[0]" :to="app[2]" class="app-icon"><span class="circle"><van-icon :name="app[1]"/></span><span>{{app[0]}}</span></router-link></section><h2 class="section-title">最新公告 <router-link to="/notices">查看全部</router-link></h2><section v-for="item in notices.slice(0,3)" :key="item.id" class="card notice"><span v-if="item.pinned" class="tag">置顶</span><div class="list-title">{{item.title}}</div><div class="muted">{{item.publisher}} · {{item.publishTime?.slice(0,10)}}</div></section></div></template>
<style scoped>.hero{height:132px;border-radius:22px;padding:26px 22px;display:flex;justify-content:space-between;align-items:flex-start}.hello{font-size:23px;font-weight:750;margin-bottom:8px}.muted-light{opacity:.78;font-size:13px}.stats{margin:-32px 14px 0;position:relative}.section-title{display:flex;justify-content:space-between}.section-title a{font-size:12px;color:#6c8b91;text-decoration:none;font-weight:400}.app-icon{text-decoration:none}.notice{position:relative}.notice .tag{position:absolute;right:16px;top:16px}</style>
