<!-- Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. -->
<script setup>
import { ref } from 'vue'
import { api } from '../api/oa'
const groups=[{title:'日常办公',items:[['考勤打卡','clock-o','/attendance'],['请假审批','records-o','/leave'],['我的待办','todo-list-o','/tasks'],['企业公告','volume-o','/notices']]},{title:'组织协作',items:[['通讯录','friends-o','/contacts'],['会议室','desktop-o',''],['用章申请','medal-o',''],['报销申请','balance-list-o','']]}]
const portfolio=ref(null),loading=ref(false)
async function analyze(){loading.value=true;try{portfolio.value=await api.approvalPortfolio({requests:[{processName:'采购合同审批',pendingHours:30,slaHours:24,businessImpact:88,vipApplicant:true,missingMaterials:false},{processName:'差旅报销',pendingHours:8,slaHours:24,businessImpact:30,vipApplicant:false,missingMaterials:false},{processName:'用章申请',pendingHours:20,slaHours:24,businessImpact:70,vipApplicant:false,missingMaterials:true}],teams:[{teamName:'综合审批组',dailyCapacity:3,activeLoad:2},{teamName:'财务审批组',dailyCapacity:2,activeLoad:1}]})}finally{loading.value=false}}
</script>
<template><div class="page safe-top"><h1 class="page-title">工作台</h1><section v-for="group in groups" :key="group.title" class="card"><div class="section-heading">{{group.title}}</div><div class="grid"><component :is="item[2]?'router-link':'div'" v-for="item in group.items" :key="item[0]" :to="item[2]" class="app-icon" :class="{disabled:!item[2]}"><span class="circle"><van-icon :name="item[1]"/></span><span>{{item[0]}}</span></component></div></section><section class="card approval-card"><div class="approval-head"><div><b>审批负载智能分流</b><small>综合风险、SLA 与审批组容量生成路由建议</small></div><button @click="analyze" :disabled="loading">{{loading?'分析中':'运行分析'}}</button></div><div v-if="portfolio" class="approval-result"><span><b>{{portfolio.totalRequests}}</b>待审批</span><span><b>{{portfolio.breachedRequests}}</b>已超时</span><span><b>{{portfolio.unassignedRequests}}</b>待分派</span><p>{{portfolio.recommendation}}</p></div></section><div class="version">ZhuaTech OA Community v1.1.0</div></div></template>
<style scoped>.section-heading{font-weight:700;margin-bottom:18px}.app-icon{text-decoration:none}.disabled{opacity:.4}.approval-card{padding:18px}.approval-head{display:flex;align-items:center;justify-content:space-between;gap:14px}.approval-head div{display:flex;flex-direction:column;gap:5px}.approval-head small{color:#7f8d96;font-size:11px}.approval-head button{border:0;border-radius:10px;background:#2856a8;color:white;padding:9px 12px}.approval-result{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:16px}.approval-result span{padding:10px;border-radius:10px;background:#f0f4f9;color:#607080;font-size:10px}.approval-result b{display:block;color:#1f3656;font-size:19px}.approval-result p{grid-column:1/-1;margin:4px 0 0;color:#b06427;font-size:11px}.version{text-align:center;color:#a0adb1;font-size:12px;margin:30px 0}</style>
